Fix stdout fails when redirected or piped
This patch fixes when stdout is redirected or piped; e.g.,
$ bikeshed spec Overview.bs - > a

FATAL ERROR: Something prevented me from saving the output document to -:
'ascii' codec can't encode character u'\xa7' in position 729: ordinal not in range(128)
WARNING: Your console does not understand Unicode.
  Messages may be slightly corrupted.
 &#10008;  Did not generate, due to fatal errors